# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - id: foo
      uses: kirogum/solid-couscous@v2
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
    - uses: ./.github/actions/hello
      with:
        who-to-greet: 'Mona the Octhahahahahahaocat'
